config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'menus/index'
  root to: "menus#index"
  resources :menus do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end

  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :menu
  belongs_to :user 

  validates :comment_text, presence: true
end

app/models/hour.rb
class Hour < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '5分' },
    { id: 3, name: '10分' },
    { id: 4, name: '15分' },
    { id: 5, name: '20分' },
    { id: 6, name: '25分' },
    { id: 7, name: '30分' },
    { id: 8, name: '35分' },
    { id: 9, name: '40分' },
    { id: 10, name: '45分' },
    { id: 11, name: '50分' },
    { id: 12, name: '55分' },
    { id: 13, name: '60分' }
  ]

  include ActiveHash::Associations
  has_many :menus

  end

app/models/menu.rb
class Menu < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :hour
  

  belongs_to :user
  has_one_attached :image
  has_many :steps, dependent: :destroy
  accepts_nested_attributes_for :steps, allow_destroy: true
  has_many :comments

  with_options presence: true do
    validates :title
    validates :advice_text
    validates :hour_id, numericality: { other_than: 1, message: "can't be blank" }
    validates :food_first
    validates :spice
    validates :image
  end

  def self.search(search)
    if search != ""
      Menu.where(['food_first LIKE(?) OR food_second LIKE(?)',"%#{search}%","%#{search}%"])
    else
      Menu.all
    end
  end

end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :menu

  validates :step_number, presence: true
  validates :step_text, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :menus
  has_many :comments

  validates :nickname, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :basic_auth
 before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    if @comment.save
      redirect_to menu_path(@comment.menu)
    else
      @menu = @comment.menu
      @comments = @menu.comments
      render "menus/show"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:comment_text).merge(user_id: current_user.id, menu_id: params[:menu_id])
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, only: [:edit, :destroy]

  def index
    @menus = Menu.includes(:user)
  end

  def new
    @menu = Menu.new
    @step = @menu.steps.build
  end

  def create
    @menu = Menu.new(menu_params)
    if @menu.save
      redirect_to root_path(@menu)
   else
      render :new
   end   
  end

  def show
    @steps = @menu.steps.includes(:menu)
    @comment = Comment.new
    @comments = @menu.comments.includes(:user)
  end

  def search
    @menus = Menu.search(params[:keyword])
  end

  def edit
    unless current_user.id == @menu.user_id
      redirect_to action: :index
    end
  end

  def update
    if @menu.update(menu_params) 
      redirect_to menu_path
    else
      render :edit
    end
  end

  def destroy
    @menu.destroy
    redirect_to root_path
  end

  private

  def menu_params
    params.require(:menu).permit(:title, :advice_text, :hour_id, :food_first, :food_second, :spice, :image,
                                  steps_attributes:[:step_text, :step_number, :_destroy, :id]).merge(user_id: current_user.id)
  end


  def set_item
    @menu = Menu.find(params[:id])
  end

  def move_to_index
    unless current_user.id == @menu.user_id
      redirect_to action: :index
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @nickname = @user.nickname
    @menus = @user.menus
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OriginalRecipe37255</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 <body>
  <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%# <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
            <% if user_signed_in? %>
              <div class="nav__right" >
               <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
               <%= link_to "新規投稿", new_menu_path, class: :nav__btn %>
               <%= link_to "#{current_user.nickname}さん" , user_path(current_user.id), class: :nav__btn%>
              </div>
            <% else %>
              <div class="nav__right">
               <%= link_to "ログイン",  new_user_session_path, class: :nav__btn %>
               <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
              </div>
            <% end %>
        </div>
      </div>
  </header>
    <%= yield %>
  <footer class="footer">
       <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
  </footer>
 </body>
</html>

app/views/menus/_form.html.erb
<%= form_with(model: menu, local: true) do |f| %>
  <div class="field">
    <%= f.label :title, "レシピ名" %><br />
    <%= f.text_field :title, id:"menu_title" %>
  </div>

  <div class="field">
    <%= f.label :image, "レシピの画像" %><br />
    <%= f.file_field :image, id:"menu_image" %>
  </div>

  <div class="field">
    <%= f.label :advice_text, "レシピの説明" %><br />
    <%= f.text_area :advice_text, class: :form__text, id:"menu_advice_text" %>
  </div>

  <div class="weight-bold-text">調理時間</div>
  <%= f.collection_select(:hour_id, Hour.all, :id, :name, {}, {class:"select-box", id:"menu-hour"}) %>

  <div class="field">
    <%= f.label :food_first, "材料１" %><br />
    <%= f.text_field :food_first, placeholder: "例にんじん", id:"menu_food_first" %>
  </div>

  <div class="field">
   <%= f.label :food_second, "材料２" %><br />
    <%= f.text_field :food_second,placeholder: "例じゃがいも", id:"menu_food_second" %>
  </div>

  <div class="field">
    <%= f.label :spice, "調味料" %><br />
    <%= f.text_area :spice, class: :form__text, id:"menu_spice" %>
  </div>

  <div class="recipe-ingredients">
      <div class="mx-auto">
        <%= f.fields_for :steps do |t| %>
          <%= render "menus/step_fields", f: t %>
        <% end %>
      </div>

      <div id="detail-association-insertion-point"></div>

      <div class="col-10 mx-auto mt-2">
        <%= link_to_add_association "+フォームを追加", f, :steps,
        class: "btn btn-secondary btn-block",
        data: {
        association_insertion_node: '#detail-association-insertion-point',
        association_insertion_method: 'after'
        }%>
      </div>
  </div>


  
  <div class="actions">
    <%= f.submit "投稿する", class: :form__btn  %>
  </div>

<% end %>

app/views/menus/_menu.html.erb
<div class="card">
  <%=link_to image_tag(menu.image, class: "card__img"), menu_path(menu.id) %>
  <div class="card__body">
    <%= link_to menu.title, menu_path(menu.id), class: :card__title%>
    <p class="card__summary">
      <%= menu.food_first %>,
      <%= menu.food_second %>
    </p>
    <%= link_to "by #{menu.user.nickname}", user_path(menu.user_id), class: :card__user %>
  </div>
</div>

app/views/menus/_step_fields.html.erb
<div class="nested-fields">
  <div class="row mx-auto">
    作り方
    <div class="col-5">
    <%= f.text_area :step_text, class: "form-control", placeholder: "手順" %></div>
    手順番号
    <div class="offset-1 col-2"><%= f.text_field :step_number, class: "form-control", placeholder: "例)1" %></div>
    <div class="offset-1 col-1 px-0 w-auto">
      <%= link_to_remove_association "削除", f, class: "btn btn-secondary btn-block" %>
    </div>
  </div>
</div>

app/views/menus/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">レシピ編集</h2>
        <%= render partial: 'form', locals: { menu: @menu } %>
    </div>
  </div>
</div>

app/views/menus/index.html.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
      <div class="greeting">
         こんにちは、
        <%= link_to "#{current_user.nickname}さん" , user_path(current_user), class: :greeting__link%>
      </div>
    <% end %>  

    <%= form_with(url: search_menus_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder: "食材を検索する", class: "search-input" %>
      <%= form.submit "検索", class: "search-btn" %>
    <% end %>

    <div class="card__wrapper">
      <%= render partial: 'menu', collection: @menus  %>
    </div>
  </div>
</main>

app/views/menus/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規レシピ投稿</h2>
        <%# 部分テンプレートでフォームを表示する %>
        <%= render partial: 'form', locals: { menu: @menu } %>
    </div>
  </div>
</div>

app/views/menus/search.html.erb
<main class="main">
  <div class="inner">
    <%= form_with(url: search_menus_path, local: true, method: :get, class: "search-form") do |form| %>
     <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
     <%= form.submit "検索", class: "search-btn" %>
    <% end %>
    <h2 class="page-heading">
      検索結果
    </h2>
    <div class="card__wrapper">
      <% @menus.each do |menu| %>
       <%= render partial: "menu", locals: { menu: menu } %>
      <% end %>
    </div>
    <%= link_to "戻る", menus_index_path, class: :back__btn %>
  </div>
</main>

app/views/menus/show.html.erb
<main class="main">
  <div class="inner">
    <div class="menu__wrapper">
      <p class="menu__hedding">
        <%= @menu.title %>
      </p>
      <%= link_to "by #{@menu.user.nickname}", user_path(@menu.user.id), class: :menu__user %>
   
       <% if user_signed_in? && current_user.id == @menu.user_id %>
        <div class="menu__manage">
          <%= link_to "編集する", edit_menu_path, class: :menu__btn %>
          <%= link_to "削除する", "#", method: :delete, class: :menu__btn %>
        </div>
        <% end %>

      <div class="menu__image">
        <%= image_tag @menu.image %>
      </div>
      <div class="menu__body">
        <div class="menu__detail">
          <p class="detail__title">レシピの説明</p>
          <p class="detail__message">
            <%= @menu.advice_text %>
          </p>
      

          <p class="detail__title">材料</p>
          <p class="detail__message">
            <%= @menu.food_first %>
          </p>
          <p class="detail__message">
            <%= @menu.food_second %>
          </p>

          <p class="detail__title">調味料</p>
          <p class="detail__message">
            <%= @menu.spice %>
          </p>

          <p class="detail__title">作り方</p>
          <p class="detail__message">
           <% @steps.each do |step| %>
            <li class="comments_list">
               <%= step.step_number %>.
               <%= step.step_text %>
            </li>
            <% end %>
          </p>
        </div>
      </div>
    </div>
    <div class="menu__comments">
        <% if user_signed_in? %>
          <%= form_with model: [@menu,@comment],local: true do |f|%>
            <div class="field">
               <%= f.label :作ってみたコメント %><br />
               <%= f.text_field :comment_text %>
            </div>
            <div class="actions">
               <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %>
        <% end %>  
        <ul class="comments_lists">
            <% @comments.each do |comment| %>
            <li class="comments_list">
               <%= comment.comment_text %>
               <%= link_to comment.user.nickname, user_path(comment.user.id), class: :comment_user %>  
            </li>
            <% end %>
        </ul>
      </div>

    <%= link_to "戻る", menus_index_path, class: :back__btn %>
  </div>
</div>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@nickname}さんの投稿レシピ"%>
      </h2>
      <div class="user__card">
        <%= render partial:'menus/menu', collection: @menus %>
      </div>

      <%= link_to "戻る", menus_index_path, class: :back__btn %>
    </div>
  </div>
</div>